<a href="https://colab.research.google.com/github/173479/mineriaDeDatos/blob/main/Mineria_De_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## Primer parcial

### Introducción

#### Conceptos

que es la mineria de datos ?
  es la extraccion de datos con informacion util de una acumulacion de datos para poder analizar tendencias o patrones, en donde se pueden usar tecnicas de estadistica o sistemas de informacion para lograr ver distintos tipos de anomalias

que es la ciencia de datos?
  la ciencia de los datos es un campo que usa distintos metodos, procesos y sistemas, para extraer informacion valiosa en grandes cantidades de datos, lo que viene a ser BIG DATA

#### Ciencia de Datos

Help and Documentation in IPython

In [ ]:
#la funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
#Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:
#Otro ejemplo de ayuda
L?

In [ ]:
#Ejemplo con una funcion con Docstring
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
help (square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
#ejemplo de ayuda de funcion personalizada
square??

In [ ]:
#ejemplo con funcion built-in
len??

In [ ]:
#ejemplo de autocompletado
L.insert

<function list.insert(index, object, /)>

In [ ]:
#otro ejemplo de autocompletado
from itertools import combinations

IPython Magic Commands

In [5]:
#mide el tiempo en el que se ejecuta la instruccion y mide el desempeño en
# promedio sirve para expresiones de una sola linea al usarse con solo un %
%timeit L = [n ** 2 for n in range(1000)]

86.6 µs ± 22.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
#sirve para lo mismo que el anterior pero para expresiones de mas de una linea
# por eso se usa doble %%
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)


94.2 µs ± 27.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [8]:
#muestra los archivos que estan en el directorio en el que estamos
!ls

sample_data


In [9]:
#nos da la ruta en la que estamos
!pwd

/content


In [10]:
#nos permite escribir en la consola
!echo "printing from the shell"

printing from the shell


In [11]:
#guarda lo que tenemos en el directorio
contents = !ls

In [12]:
print(contents)

['sample_data']


In [13]:
#guarda en una variable el directorio en el que estamos
directory = !pwd

In [14]:
print(directory)

['/content']


In [15]:
#ayuda a saber el tipo del directorio en el que se aguardo la variable
type(directory)

IPython.utils.text.SList

In [16]:
#guarda un mensaje en una variable
message = "hello from Python"


In [17]:
!echo {message}

hello from Python


In [18]:
#cambia el directorio en el que estamos
%cd /content/

/content


In [19]:
%ls

sample_data/


In [20]:
%cd sample_data/

/content/sample_data


In [21]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [22]:
#sirve para visualizar el archivo
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


Understanding Data Types in Python

In [26]:
#importa numpy y renombralo como np (numpy genera arrays de n dimensiones)
import numpy as np

In [25]:
#arreglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [28]:
#al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [29]:
#genera los elementos segun el tipo que le definamos
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [30]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [32]:
#genera un rango dando el inicio y el limite en este caso dando un caso en especifico, generando una matriz bidimencional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])